AWSTemplateFormatVersion: '2010-09-09'
Description: Ancient-evil-bo4

Resources:
    Ec2Instance:
        Type: AWS::EC2::Instance
        Properties:
          InstanceType: t2.micro
          ImageId: ami-01c835443b86fe988


